Controller
Conso97/Tutorade pull request #43
Opened 2021-08-19 05:01 UTC by ManuhuiaBarcham

Update our main branch with the work we did on the controller section tonight (08/18/2021)

2021-08-19 06:34 UTC, michellecoder requested changes
For the controllers api it should be tutor not teacher.

2021-08-19 17:28 UTC, MohamedMesahel approved these changes

2021-08-19 17:28 UTC, MohamedMesahel approved these changes

2021-08-19 20:40 UTC, MaryVPie reviewed
Please have a look at my comments

2021-08-19 20:40 UTC, MaryVPie commented on controllers/api/formsRoutes.js
> +//         res.render('newStudent',{teacherId:req.params.pid});
Here is teacherID. Please change it into tutorId

2021-08-19 20:40 UTC, MaryVPie commented on controllers/api/formsRoutes.js
> +//     app.get('/scheduleStudent', function(req, res) {
Do we still need schedule?

2021-08-19 20:40 UTC, MaryVPie commented on controllers/api/index.js
Is it a typo "s" in studentSRoutes and in /students, /tutors?

2021-08-19 20:40 UTC, MaryVPie commented on controllers/api/roleRoutes.js
> +//       include: [db.Teacher, db.Schedule]
db.Teacher -> db.Tutuor

2021-08-19 20:40 UTC, MaryVPie commented on controllers/api/roleRoutes.js
> +//       include: [db.Teacher, db.Schedule]
db.Teacher -> db.Tutuor

2021-08-19 20:40 UTC, MaryVPie commented on controllers/api/roleRoutes.js
> +//         pid: req.body.TeacherId
Teacher -> Tutuor

2021-08-19 20:40 UTC, MaryVPie commented on controllers/api/roleRoutes.js
> +//     db.Student.destroy({
What is child here?

2021-08-19 20:40 UTC, MaryVPie commented on controllers/homeRoutes.js
> +          attributes: ['name'],
Do we use first name and last name?

2021-08-20 00:06 UTC, michellecoder approved these changes

2021-08-20 00:07 UTC, merged